[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "rbm-review"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
lint.select = [
    "D",   # pydocstyle rules
]
line-length = 80

[tool.ruff.lint.pydocstyle]
convention = "google"

