# config/train.yaml
training:
  batch_size: 64
  n_epochs: 5
  lr: 0.05
  k: 1
  pcd: True
  mc: "mean-field"  # could be 'mean-field' or 'gibbs' or 'langevin'
  epsilon: 1e-5  # only used for langevin dynamics. step size for the updates.

data:
  type: cifar10   # could be 'mnist', 'stl10', 'cifar10', 'ising', 'xy', 'potts', etc.
  path: ./data
  
model:
  type: binary  # could be 'binary', 'exponential', 'gaussian', 'multinomial', 'vonmises', etc.
  n_visible: 784
  n_hidden: 8

output_dir: ./outputs