# config/mnist.yaml
data:
  data_type: mnist
  data_dir: "data"
  batch_size: 64
  split: 0.8
  
model:
  model_type: gaussian
  n_hidden: 512

training:
  n_epochs: 100
  lr: 0.0001
  k: 10
  algorithm: "SM"
  mc: "gibbs"

output:
  base_dir: "outputs"
  run_name: "mnist_run"